
from pathlib import Path
import pathlib
import json
from dash_service.utils import get_geo_file

config_file_path = (
    f"{pathlib.Path(__file__).parent.parent.absolute()}/static/indicator_config.json"
)
with open(config_file_path) as config_file:
    indicators_config = json.load(config_file)


geo_json_countries = get_geo_file("ecaro.geo.json")

graphs_dict = {
    "bar": {
        "options": dict(
            x="Country_name",
            y="OBS_VALUE",
            barmode="group",
            text="OBS_VALUE",
            custom_data=[
                "OBS_VALUE",
                "Country_name",
                "TIME_PERIOD",
                "OBS_FOOTNOTE",
                "DATA_SOURCE",
                "Sex_name",
                "Age_name",
                "Wealth_name",
                "Residence_name",
            ],
            height=500,
            text_auto=".3s",
        ),
        "layout_options": dict(
            xaxis_title={"standoff": 0},
            margin_t=30,
            margin_b=0,
        ),
    },
    "count_bar": {
        "options": dict(
            x="Status",
            color="Status",
            color_discrete_map={"Yes": "#1CABE2", "No": "#fcba03"},
            custom_data=[
                "OBS_VALUE",
                "Country_name",
                "TIME_PERIOD",
                "OBS_FOOTNOTE",
                "DATA_SOURCE",
                "Status",
            ],
            height=450,
            width=1000,
        ),
        "layout_options": dict(
            xaxis_title={"standoff": 0},
            margin_t=50,
            margin_b=0,
        ),
    },
    "line": {
        "options": dict(
            x="TIME_PERIOD",
            y="OBS_VALUE",
            color="Country_name",
            custom_data=[
                "OBS_VALUE",
                "Country_name",
                "TIME_PERIOD",
                "OBS_FOOTNOTE",
                "DATA_SOURCE",
            ],
            line_shape="spline",
            render_mode="svg",
            height=500,
        ),
        "trace_options": dict(mode="markers+lines", line=dict(width=0.8)),
        "layout_options": dict(
            xaxis_title={"standoff": 10},
            margin_t=40,
            margin_b=0,
        ),
    },
    "map": {
        "options": dict(
            locations="REF_AREA",
            featureidkey="id",
            color="OBS_VALUE",
            mapbox_style="carto-positron",
            geojson=geo_json_countries,
            zoom=2.5,
            center={"lat": 51.9194, "lon": 19.040236},
            opacity=0.6,
            custom_data=[
                "OBS_VALUE",
                "Country_name",
                "TIME_PERIOD",
                "OBS_FOOTNOTE",
                "DATA_SOURCE",
            ],
            height=500,
            width=None,
        ),
        "layout_options": dict(margin={"r": 0, "t": 80, "l": 2, "b": 5}),
    },
}




min_max_card_suffix = "min - max values"

merged_page_config = {'child-rights': {'domain_name': 'Child Rights Landscape and Governance',
                    'page_prefix': 'crg',
                    'domain_colour': '#562061',
                    'light_domain_colour': '#e7c9ed',
                    'dark_domain_colour': '#44194d',
                    'map_colour': 'purpor',
                    'SUBDOMAINS': {'DEM': {'NAME': 'Demographics',
                        'CARDS': [{'name': 'Child population (0-17 years)',
                        'indicator': 'DM_CHLD_POP',
                        'suffix': 'children',
                        'min_max': False,
                        'button_name': 'Child population'},
                        {'name': 'Percentage of children as a share of the total population',
                        'indicator': 'DM_CHLD_POP_PT',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children as a share of the total population'},
                        {'name': 'Number of births',
                        'indicator': 'DM_BRTS',
                        'suffix': 'births',
                        'min_max': False,
                        'button_name': 'Number of births'},
                        {'name': 'Total fertility rate',
                        'indicator': 'DM_FRATE_TOT',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Total fertility rate'},
                        {'name': 'Net migration',
                        'indicator': 'DM_POP_NETM',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Net migration'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['DM_CHLD_POP',
                        'DM_CHLD_POP_PT',
                        'DM_BRTS',
                        'DM_FRATE_TOT',
                        'DM_POP_NETM'],
                        'default_graph': 'bar',
                        'default': 'DM_CHLD_POP'}},
                    'PLE': {'NAME': 'Political economy',
                        'CARDS': [{'name': 'Human Development Index',
                        'indicator': 'EC_HDI',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Human Development Index'},
                        {'name': 'Total general government expenditure (% of GDP)',
                        'indicator': 'EC_TEC_GRL_GOV_EXP',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Total general government expenditure'},
                        {'name': 'GDP per capita, PPP (current international $)',
                        'indicator': 'EC_NY_GDP_PCAP_PP_CD',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'GDP per capita, PPP'},
                        {'name': 'GNI per capita, Atlas method (current US$)',
                        'indicator': 'EC_NY_GNP_PCAP_CD',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'GNI per capita, Atlas method'},
                        {'name': 'Gini coefficient of equivalised disposable income (Eurostat estimate)',
                        'indicator': 'PV_GINI_COEF',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Gini Index'},
                        {'name': 'Unemployment, modelled ILO estimate (% of total labour force) - SDG 8.5.2',
                        'indicator': 'EC_SL_UEM_TOTL_ZS',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Unemployment, modelled ILO estimate (SDG 8.5.2)'},
                        {'name': 'Labour force participation rate',
                        'indicator': 'EC_EAP_RT',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Labour force participation rate'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['EC_HDI',
                        'EC_TEC_GRL_GOV_EXP',
                        'EC_NY_GDP_PCAP_PP_CD',
                        'EC_NY_GNP_PCAP_CD',
                        'PV_GINI_COEF',
                        'EC_SL_UEM_TOTL_ZS',
                        'EC_EAP_RT'],
                        'default_graph': 'bar',
                        'default': 'EC_HDI'}},
                    'CRG': {'NAME': 'Child rights governance',
                        'CARDS': [{'name': 'Countries with National Human Rights Institutions in compliance with the Paris Principles (A status) - SDG 16.a.1',
                        'indicator': 'PP_SG_NHR_IMPLN',
                        'suffix': 'countries in compliance with the Paris Principles',
                        'min_max': False,
                        'button_name': 'Status of National Human Rights Institutions (SDG 16.a.1)'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['PP_SG_NHR_IMPLN'],
                        'default_graph': 'map',
                        'default': 'PP_SG_NHR_IMPLN'}},
                    'SPE': {'NAME': 'Public spending on children',
                        'CARDS': [{'name': 'Government expenditure on education (% of GDP) (public spending sub-domain)',
                        'indicator': 'EDU_FIN_EXP_PT_GDP-SPE',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Government expenditure on education'},
                        {'name': 'Expenditure on pre-primary (% of government expenditure on education)',
                        'indicator': 'EDU_FIN_EXP_L02',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Expenditure on pre-primary education'},
                        {'name': 'Expenditure on primary (% of government expenditure on education)',
                        'indicator': 'EDU_FIN_EXP_L1',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Expenditure on primary education'},
                        {'name': 'Domestic general government health expenditure (% of GDP) (public spending sub-domain)',
                        'indicator': 'HT_SH_XPD_GHED_GD_ZS-SPE',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Domestic general government health expenditure'},
                        {'name': 'General government expenditure by function: Social protection (% of GDP)',
                        'indicator': 'EC_SP_GOV_EXP_GDP',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'General government expenditure on social protection'},
                        {'name': 'Expenditure on family-children benefits (% of expenditure on social benefits) (public spending sub-domain)',
                        'indicator': 'EC_EXP_FAM_CHLD_EXP-SPE',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Expenditure on family-children benefits'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['EDU_FIN_EXP_PT_GDP-SPE',
                        'EDU_FIN_EXP_L02',
                        'EDU_FIN_EXP_L1',
                        'HT_SH_XPD_GHED_GD_ZS-SPE',
                        'EC_SP_GOV_EXP_GDP',
                        'EC_EXP_FAM_CHLD_EXP-SPE'],
                        'default_graph': 'bar',
                        'default': 'EDU_FIN_EXP_PT_GDP-SPE'}},
                    'DTA': {'NAME': 'Data on children',
                        'CARDS': [{'name': 'Statistical capacity score',
                        'indicator': 'CR_IQ_SCI_OVRL',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Statistical capacity score'},
                        {'name': 'Countries with national statistical legislation exists that complies with the Fundamental Principles of Official Statistics - SDG 17.18.2',
                        'indicator': 'CR_SG_STT_FPOS',
                        'suffix': 'countries',
                        'min_max': False,
                        'button_name': 'Compliance of national statistical legislation (SDG 17.18.2)'},
                        {'name': 'Value of all resources made available to strengthen statistical capacity in developing countries (current US$) - SDG 17.19.1',
                        'indicator': 'CR_SG_STT_CAPTY',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Value of resources to strengthen statistical capacity (SDG 17.19.1)'},
                        {'name': 'Countries with national statistical plans that are fully funded - SDG 17.18.3',
                        'indicator': 'CR_SG_STT_NSDSFND',
                        'suffix': 'countries',
                        'min_max': False,
                        'button_name': 'National statistical plans that are fully funded (SDG 17.18.3)'},
                        {'name': 'Countries with national statistical plans that are under implementation - SDG 17.18.3',
                        'indicator': 'CR_SG_STT_NSDSIMPL',
                        'suffix': 'countries',
                        'min_max': False,
                        'button_name': 'National statistical plans that are under implementation (SDG 17.18.3)'},
                        {'name': 'Countries with national statistical plans with funding from government - SDG 17.18.3',
                        'indicator': 'CR_SG_STT_NSDSFDGVT',
                        'suffix': 'countries',
                        'min_max': False,
                        'button_name': 'National statistical plans with funding from government (SDG 17.18.3)'},
                        {'name': 'Countries with national statistical plans with funding from donors - SDG 17.18.3',
                        'indicator': 'CR_SG_STT_NSDSFDDNR',
                        'suffix': 'countries',
                        'min_max': False,
                        'button_name': 'National statistical plans with funding from donors (SDG 17.18.3)'},
                        {'name': 'Countries with national statistical plans with funding from others - SDG 17.18.3',
                        'indicator': 'CR_SG_STT_NSDSFDOTHR',
                        'suffix': 'countries',
                        'min_max': False,
                        'button_name': 'National statistical plans with funding from others (SDG 17.18.3)'},
                        {'name': 'Countries that have conducted at least one population and housing census in the last 10 years - SDG 17.19.2',
                        'indicator': 'CR_SG_REG_CENSUSN',
                        'suffix': 'countries',
                        'min_max': False,
                        'button_name': 'Census (SDG 17.19.2)'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['CR_IQ_SCI_OVRL',
                        'CR_SG_STT_FPOS',
                        'CR_SG_STT_CAPTY',
                        'CR_SG_STT_NSDSFND',
                        'CR_SG_STT_NSDSIMPL',
                        'CR_SG_STT_NSDSFDGVT',
                        'CR_SG_STT_NSDSFDDNR',
                        'CR_SG_STT_NSDSFDOTHR',
                        'CR_SG_REG_CENSUSN'],
                        'default_graph': 'map',
                        'default': 'CR_IQ_SCI_OVRL'}},
                    'REM': {'NAME': 'Right to remedy',
                        'CARDS': [{'name': 'Number of children (0-17 years) who brought or on whose behalf a complaint was brought by an adult to independent human rights mechanisms during the year',
                        'indicator': 'JJ_CHLD_COMPLAINT_HHRR',
                        'suffix': 'children',
                        'min_max': False,
                        'button_name': 'Number of children who lodged a complaint a human rights complaint during the year'},
                        {'name': 'Number of children with disabilities (0-17 years) who brought or on whose behalf a complaint was brought by an adult to independent human rights mechanisms during the year',
                        'indicator': 'JJ_CHLD_DISAB_COMPLAINT_HHRR',
                        'suffix': 'children',
                        'min_max': False,
                        'button_name': 'Number of children with disabilities who lodged a complaint a human rights complaint during the year'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['JJ_CHLD_COMPLAINT_HHRR', 'JJ_CHLD_DISAB_COMPLAINT_HHRR'],
                        'default_graph': 'bar',
                        'default': 'JJ_CHLD_COMPLAINT_HHRR'}},
                    'BCR': {'NAME': 'Business and child rights',
                        'CARDS': [{'name': 'No indicators available yet for this sub-domain',
                        'indicator': 'BUSINESS-INDICATOR',
                        'suffix': 'No indicator chosen.',
                        'min_max': True,
                        'button_name': 'No indicators available yet for this sub-domain.'},],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': [],
                        'default_graph': 'bar',
                        'default': 'BUSINESS-INDICATOR'}},}},
                    'child-health': {'domain_name': 'Health and Nutrition',
                    'page_prefix': 'han',
                    'domain_colour': '#3e7c49',
                    'light_domain_colour': '#e0f0e3',
                    'dark_domain_colour': '#24472a',
                    'map_colour': 'algae',
                    'SUBDOMAINS': {'HSM': {'NAME': 'Health system',
                        'CARDS': [{'name': 'UHC Service Coverage Index - SDG 3.8.1',
                        'indicator': 'HT_UHC_IDX',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'UHC Service Coverage Index (SDG 3.8.1)'},
                        {'name': 'Current health expenditure (% of GDP)',
                        'indicator': 'HT_SH_XPD_CHEX_GD_ZS',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Current health expenditure'},
                        {'name': 'Domestic general government health expenditure (% of GDP) (health system sub-domain)',
                        'indicator': 'HT_SH_XPD_GHED_GD_ZS',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Domestic general government health expenditure'},
                        {'name': 'Domestic general government health expenditure (% of general government expenditure)',
                        'indicator': 'HT_SH_XPD_GHED_GE_ZS',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Domestic general government health expenditure (% of general government expenditure)'},
                        {'name': 'Domestic general government health expenditure per capita, PPP (current international $)',
                        'indicator': 'HT_SH_XPD_GHED_PP_CD',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Domestic general government health expenditure per capita'},
                        {'name': 'Out-of-pocket expenditure (% of current health expenditure)',
                        'indicator': 'HT_SH_XPD_OOPC_CH_ZS',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Out-of-pocket expenditure'},
                        {'name': 'Total population covered by public and primary private health insurance',
                        'indicator': 'HT_INS_COV',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Population covered by health insurance '}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['HT_UHC_IDX',
                        'HT_SH_XPD_CHEX_GD_ZS',
                        'HT_SH_XPD_GHED_GD_ZS',
                        'HT_SH_XPD_GHED_GE_ZS',
                        'HT_SH_XPD_GHED_PP_CD',
                        'HT_SH_XPD_OOPC_CH_ZS',
                        'HT_INS_COV'],
                        'default_graph': 'bar',
                        'default': 'HT_UHC_IDX'}},
                    'MNH': {'NAME': 'Maternal, newborn and child health',
                        'CARDS': [{'name': 'Neonatal mortality rate - SDG 3.2.2 (child health sub-domain)',
                        'indicator': 'CME_MRM0',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Neonatal mortality rate (SDG 3.2.2)'},
                        {'name': 'Infant mortality rate - SDG 3.2.1',
                        'indicator': 'CME_MRY0',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Infant mortality rate (SDG 3.2.1)'},
                        {'name': 'Under-five mortality rate - SDG 3.2.1',
                        'indicator': 'CME_MRY0T4',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Under-five mortality rate (SDG 3.2.1)'},
                        {'name': 'Percentage of births attended by skilled health personnel - SDG 3.1.2',
                        'indicator': 'MNCH_SAB',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Births attended by skilled health personnel (SDG 3.1.2)'},
                        {'name': 'Stillbirth rate',
                        'indicator': 'CME_SBR',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Stillbirth rate'},
                        {'name': 'C-section rate - percentage of deliveries by caesarean section',
                        'indicator': 'MNCH_CSEC',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'C-section rate'},
                        {'name': 'Prevalence of low birth weight among newborns',
                        'indicator': 'NT_BW_LBW',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Low birth weight among newborns'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['CME_MRM0',
                        'CME_MRY0',
                        'CME_MRY0T4',
                        'MNCH_SAB',
                        'CME_SBR',
                        'MNCH_CSEC',
                        'NT_BW_LBW'],
                        'default_graph': 'bar',
                        'default': 'CME_MRM0'}},
                    'IMM': {'NAME': 'Immunization',
                        'CARDS': [{'name': 'Percentage of children who received the 2nd dose of measles-containing vaccine (MCV2) - SDG 3.b.1',
                        'indicator': 'IM_MCV2',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'MCV2 coverage (SDG 3.b.1)'},
                        {'name': 'Percentage of surviving infants who received the third dose of DTP-containing vaccine (DTP3) - SDG 3.b.1',
                        'indicator': 'IM_DTP3',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'DTP3 coverage (SDG 3.b.1)'},
                        {'name': 'Percentage of surviving infants who received the third dose of pneumococcal conjugate-containing vaccine (PCV3) - SDG 3.b.1',
                        'indicator': 'IM_PCV3',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'PCV3 coverage (SDG 3.b.1)'},
                        {'name': 'Percentage of females who received the last dose of human papillomavirus (HPV) vaccine per national schedule - SDG 3.b.1',
                        'indicator': 'IM_HPV',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'HPV coverage (SDG 3.b.1)'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['IM_MCV2', 'IM_DTP3', 'IM_PCV3', 'IM_HPV'],
                        'default_graph': 'bar',
                        'default': 'IM_MCV2'}},
                    'NUT': {'NAME': 'Nutrition',
                        'CARDS': [{'name': 'Percentage of infants (under 6 months) who are exclusively breastfed (nutrition sub-domain)',
                        'indicator': 'NT_BF_EXBF',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Exclusive breastfeeding'},
                        {'name': 'Percentage of children born in the last 24 months who were put to the breast within one hour of birth',
                        'indicator': 'NT_BF_EIBF',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Early initiation of breastfeeding'},
                        {'name': 'Introduction to solid, semi-solid foods (6-8 months)',
                        'indicator': 'NT_CF_ISSSF_FL',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Introduction to solid, semi-solid foods'},
                        {'name': 'Minimum Acceptable Diet (6-23 months)',
                        'indicator': 'NT_CF_MAD',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Minimum acceptable diet'},
                        {'name': 'Overweight prevalence (weight-for-height >+2 standard deviations from the median of the WHO Child Growth Standards) among children under 5 years of age - SDG 2.2.2',
                        'indicator': 'NT_ANT_WHZ_PO2',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Prevalence of overweight (SDG 2.2.2)'},
                        {'name': 'Obesity prevalence among children and adolescents (5-19 years)',
                        'indicator': 'NT_CHLD_OBESITY',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Prevalence of obesity'},
                        {'name': 'Wasting prevalence (weight-for-height <-2 standard deviations from the median of the WHO Child Growth Standards) among children under 5 years of age - SDG 2.2.2',
                        'indicator': 'NT_ANT_WHZ_NE2',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Prevalence of wasting (SDG 2.2.2 )'},
                        {'name': 'Stunting prevalence (height-for-age <-2 standard deviations from the median of the WHO Child Growth Standards) among children under 5 years of age - SDG 2.2.2',
                        'indicator': 'NT_ANT_HAZ_NE2',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Prevalence of stunting (SDG 2.2.1 )'},
                        {'name': 'Percentage of women (15-49 years) with anaemia - SDG 2.2.3',
                        'indicator': 'HT_SH_STA_ANEM',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Anaemia among women (SDG 2.2.3 )'},
                        {'name': 'Prevalence of anaemia in children (6–59 months)',
                        'indicator': 'HT_ANEM_U5',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Anaemia among children under 5 years'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['NT_BF_EXBF',
                        'NT_BF_EIBF',
                        'NT_CF_ISSSF_FL',
                        'NT_CF_MAD',
                        'NT_ANT_WHZ_PO2',
                        'NT_CHLD_OBESITY',
                        'NT_ANT_WHZ_NE2',
                        'NT_ANT_HAZ_NE2',
                        'HT_SH_STA_ANEM',
                        'HT_ANEM_U5'],
                        'default_graph': 'bar',
                        'default': 'NT_BF_EXBF'}},
                    'ADO': {'NAME': 'Adolescent physical, mental and reproductive health',
                        'CARDS': [{'name': 'Adolescent birth rate - SDG 3.7.2 (adolescent health sub-domain)',
                        'indicator': 'FT_SP_DYN_ADKL',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Adolescent birth rate (SDG 3.7.2)'},
                        {'name': 'Adolescent mortality rate',
                        'indicator': 'HT_ADOL_MT',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Adolescent mortality rate'},
                        {'name': 'Suicide mortality rate - SDG 3.4.2 (adolescent health sub-domain)',
                        'indicator': 'MT_SDG_SUICIDE',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Suicide rate (SDG 3.4.2)'},
                        {'name': 'Percentage of 15-year-old students who report doing the WHO-recommended duration of daily exercise',
                        'indicator': 'HT_CHLD_DAILY_EXER',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'WHO-recommended daily exercise'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['FT_SP_DYN_ADKL',
                        'HT_ADOL_MT',
                        'MT_SDG_SUICIDE',
                        'HT_CHLD_DAILY_EXER'],
                        'default_graph': 'bar',
                        'default': 'FT_SP_DYN_ADKL'}},
                    'HIV': {'NAME': 'HIV/AIDS',
                        'CARDS': [{'name': 'Estimated number of children  (0-19 years) living with HIV',
                        'indicator': 'HVA_EPI_LHIV_0-19',
                        'suffix': 'estimated children living with HIV',
                        'min_max': False,
                        'button_name': 'Children living with HIV'},
                        {'name': 'Estimated incidence rate among children (0-14 years) - SDG 3.3.1',
                        'indicator': 'HVA_EPI_INF_RT_0-14',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'New HIV infections (SDG 3.3.1) '},
                        {'name': 'Estimated number of annual AIDS-related deaths among children (0-19 years)',
                        'indicator': 'HVA_EPI_DTH_ANN_0-19',
                        'suffix': 'estimated AIDS-related deaths',
                        'min_max': False,
                        'button_name': 'Annual AIDS-related deaths'},
                        {'name': 'Mother-to-child HIV transmission rate',
                        'indicator': 'HVA_PMTCT_MTCT',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Mother-to-child HIV transmission rate'},
                        {'name': 'Percentage of pregnant women presenting at antenatal clinics who were tested for HIV or already knew their HIV positive status',
                        'indicator': 'HVA_PMTCT_STAT_CVG',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Pregnant women and HIV testing'},
                        {'name': 'Percentage of children (0-14 years) living with HIV and receiving antiretroviral therapy',
                        'indicator': 'HVA_PED_ART_CVG',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children receiving ART'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['HVA_EPI_LHIV_0-19',
                        'HVA_EPI_INF_RT_0-14',
                        'HVA_EPI_DTH_ANN_0-19',
                        'HVA_PMTCT_MTCT',
                        'HVA_PMTCT_STAT_CVG',
                        'HVA_PED_ART_CVG'],
                        'default_graph': 'bar',
                        'default': 'HVA_EPI_LHIV_0-19'}}}},
                    'child-education': {'domain_name': 'Education, Leisure and Culture',
                    'page_prefix': 'edu',
                    'domain_colour': '#37568f',
                    'light_domain_colour': '#bdcbe5',
                    'dark_domain_colour': '#1d2c49',
                    'map_colour': 'ice_r',
                    'SUBDOMAINS': {'ESY': {'NAME': 'Education system',
                        'CARDS': [{'name': 'Government expenditure on education (% of GDP) (education system sub-domain)',
                        'indicator': 'EDU_FIN_EXP_PT_GDP',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Government expenditure on education'},
                        {'name': 'Number of years of free pre-primary education guaranteed in legal framework',
                        'indicator': 'EDU_SDG_FREE_EDU_L02',
                        'suffix': 'countries guaranteeing at least one year',
                        'min_max': False,
                        'button_name': 'Years of free pre-primary education'},
                        {'name': 'Number of years of compulsory pre-primary education guaranteed in legal framework',
                        'indicator': 'EDU_SDG_COMP_EDU_L02',
                        'suffix': 'countries guaranteeing at least one year',
                        'min_max': False,
                        'button_name': 'Years of compulsory pre-primary education'},
                        {'name': 'Administration of nationally-representative learning assessment in math (end of primary education)',
                        'indicator': 'EDUNF_ADMIN_L1_GLAST_MAT',
                        'suffix': 'countries',
                        'min_max': False,
                        'button_name': 'Learning assessments in math (end of primary education)'},
                        {'name': 'Administration of nationally-representative learning assessment in reading (end of primary education)',
                        'indicator': 'EDUNF_ADMIN_L1_GLAST_REA',
                        'suffix': 'countries',
                        'min_max': False,
                        'button_name': 'Learning assessments in reading (end of primary education)'},
                        {'name': 'Administration of nationally-representative learning assessment in math (end of lower secondary education)',
                        'indicator': 'EDUNF_ADMIN_L2_MAT',
                        'suffix': 'countries',
                        'min_max': False,
                        'button_name': 'Learning assessments in math (end of lower secondary education)'},
                        {'name': 'Administration of nationally-representative learning assessment in reading (end of lower secondary education)',
                        'indicator': 'EDUNF_ADMIN_L2_REA',
                        'suffix': 'countries',
                        'min_max': False,
                        'button_name': 'Learning assessments in reading (end of lower secondary education)'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['EDU_FIN_EXP_PT_GDP',
                        'EDUNF_ADMIN_L1_GLAST_MAT',
                        'EDUNF_ADMIN_L1_GLAST_REA',
                        'EDUNF_ADMIN_L2_MAT',
                        'EDUNF_ADMIN_L2_REA',
                        'EDU_SDG_FREE_EDU_L02',
                        'EDU_SDG_COMP_EDU_L02'],
                        'default_graph': 'bar',
                        'default': 'EDU_FIN_EXP_PT_GDP'}},
                    'EPA': {'NAME': 'Education access and participation',
                        'CARDS': [{'name': 'Primary education completion rate - SDG 4.1.2',
                        'indicator': 'EDUNF_CR_L1',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Completion rate - primary education (SDG 4.1.2)'},
                        {'name': 'Lower secondary education completion rate - SDG 4.1.2',
                        'indicator': 'EDUNF_CR_L2',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Completion rate - lower secondary education (SDG 4.1.2)'},
                        {'name': 'Upper secondary education completion rate - SDG 4.1.2 (education access sub-domain)',
                        'indicator': 'EDUNF_CR_L3',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Completion rate - upper secondary education (SDG 4.1.2)'},
                        {'name': 'Out-of-school rate for children one year younger than the official entry age to primary education',
                        'indicator': 'EDUNF_ROFST_L1_UNDER1',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Out-of-school rate - one year younger than entry age to primary education '},
                        {'name': 'Out-of-school rate for children of primary school age',
                        'indicator': 'EDUNF_ROFST_L1',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Out-of-school rate - primary school age '},
                        {'name': 'Out-of-school rate for adolescents of lower secondary school age',
                        'indicator': 'EDUNF_ROFST_L2',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Out-of-school rate - lower secondary school age'},
                        {'name': 'Out-of-school rate for youth of upper secondary school age',
                        'indicator': 'EDUNF_ROFST_L3',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Out-of-school rate - upper secondary school age'},
                        {'name': 'Participation in organized learning (adjusted net enrolment rate, one year before official primary entry age - administrative data) - SDG 4.2.2 (education access sub-domain)',
                        'indicator': 'EDUNF_NERA_L1_UNDER1',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Participation in organized learning - administrative data (SDG 4.2.2)'},
                        {'name': 'Pupils from age 3 to the starting age of compulsory education at primary level (education access sub-domain)',
                        'indicator': 'ECD_EARLY_EDU',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Pupils from age 3 to the starting age of compulsory education at primary level'},
                        {'name': 'Percentage of primary schools with access to adapted infrastructure and materials for students with disabilities - SDG 4.a.1 (education access sub-domain)',
                        'indicator': 'EDU_SDG_SCH_L1',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Primary schools adapted infrastructure and materials (SDG 4.a.1)'},
                        {'name': 'Percentage of lower secondary schools with access to adapted infrastructure and materials for students with disabilities - SDG 4.a.1 (education access sub-domain)',
                        'indicator': 'EDU_SDG_SCH_L2',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Lower secondary schools with adapted infrastructure and materials (SDG 4.a.1)'},
                        {'name': 'Percentage of upper secondary schools with access to adapted infrastructure and materials for students with disabilities - SDG 4.a.1 (education access sub-domain)',
                        'indicator': 'EDU_SDG_SCH_L3',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Upper secondary schools with adapted infrastructure and materials (SDG 4.a.1)'},
                        {'name': 'Percentage of early leavers from education and training',
                        'indicator': 'EDAT_LFSE_14',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Early leavers from education and training'},
                        {'name': 'Participation rate of youth and adults in formal and non-formal education and training - SDG 4.3.1',
                        'indicator': 'EDU_SDG_PRYA',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Youth and adults in education and training (SDG 4.3.1)'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['EDUNF_CR_L1',
                        'EDUNF_CR_L2',
                        'EDUNF_CR_L3',
                        'EDUNF_ROFST_L1_UNDER1',
                        'EDUNF_ROFST_L1',
                        'EDUNF_ROFST_L2',
                        'EDUNF_ROFST_L3',
                        'EDUNF_NERA_L1_UNDER1',
                        'ECD_EARLY_EDU',
                        'EDU_SDG_SCH_L1',
                        'EDU_SDG_SCH_L2',
                        'EDU_SDG_SCH_L3',
                        'EDAT_LFSE_14',
                        'EDU_SDG_PRYA'],
                        'default_graph': 'bar',
                        'default': 'EDUNF_CR_L1'}},
                    'EQU': {'NAME': 'Learning quality and skills',
                        'CARDS': [{'name': 'Percentage of 15-year-olds achieving low scores in mathematics',
                        'indicator': 'EDU_PISA_LOW_ACHIEVE_MAT',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': '15-year-olds achieving low scores in mathematics'},
                        {'name': 'Percentage of 15-year-olds achieving low scores in reading',
                        'indicator': 'EDU_PISA_LOW_ACHIEVE_REA',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': '15-year-olds achieving low scores in reading'},
                        {'name': 'Percentage of 15-year-olds achieving low scores in science',
                        'indicator': 'EDU_PISA_LOW_ACHIEVE_SCI',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': '15-year-olds achieving low scores in science'},
                        {'name': 'Percentage of children at the end of lower secondary education reaching minimum proficiency in math - SDG 4.1.1 (learning sub-domain)',
                        'indicator': 'EDU_SDG_STU_L2_GLAST_MAT',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children at the end of lower secondary education reaching minimum proficiency in math (SDG 4.1.1)'},
                        {'name': 'Percentage of children at the end of lower secondary education reaching minimum proficiency in reading - SDG 4.1.1 (learning sub-domain)',
                        'indicator': 'EDU_SDG_STU_L2_GLAST_REA',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children at the end of lower secondary education reaching minimum proficiency in reading (SDG 4.1.1)'},
                        {'name': 'Percentage of youth (15-24 years) not in education, employment or training - SDG 8.6.1 (learning sub-domain)',
                        'indicator': 'EDU_SDG_YOUTH_NEET',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': ' Percentage of youth not in education, employment or training (SDG 8.6.1)'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['EDU_PISA_LOW_ACHIEVE_MAT',
                        'EDU_PISA_LOW_ACHIEVE_REA',
                        'EDU_PISA_LOW_ACHIEVE_SCI',
                        'EDU_SDG_STU_L2_GLAST_MAT',
                        'EDU_SDG_STU_L2_GLAST_REA',
                        'EDU_SDG_YOUTH_NEET'],
                        'default_graph': 'bar',
                        'default': 'EDU_PISA_LOW_ACHIEVE_MAT'}},
                    'ELE': {'NAME': 'Leisure and culture',
                        'CARDS': [{'name': 'Percentage of 15-year-old students who watch TV or play video games, before or after school',
                        'indicator': 'PP_ADOL_TVGM',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Adolescents who watch TV or play video games before or after school'},
                        {'name': 'Percentage of 15-year-old students who use the internet and social networks, before or after school',
                        'indicator': 'PP_ADOL_INET',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Adolescents who use the internet and social networks before or after school'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['PP_ADOL_TVGM', 'PP_ADOL_INET'],
                        'default_graph': 'bar',
                        'default': 'PP_ADOL_TVGM'}}}},
                    'child-protection': {'domain_name': 'Family Environment and Protection',
                    'page_prefix': 'chp',
                    'domain_colour': '#e5ae4c',
                    'light_domain_colour': '#f4daaf',
                    'dark_domain_colour': '#9c6b16',
                    'map_colour': 'YlOrBr',
                    'SUBDOMAINS': {'VIO': {'NAME': 'Violence against children and women',
                        'CARDS': [{'name': 'Percentage of children (1-14 years) who experienced any physical punishment and/or psychological aggression by caregivers - SDG 16.2.1 (violence sub-domain)',
                        'indicator': 'PT_CHLD_1-14_PS-PSY-V_CGVR',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Physical punishment and/or psychological aggression by caregivers (SDG 16.2.1)'},
                        {'name': 'Percentage of adults who think that physical punishment is necessary to raise/educate children',
                        'indicator': 'PT_ADLT_PS_NEC',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Attitudes to physical punishment'},
                        {'name': 'Percentage of ever-partnered women and girls (15 years and older) subjected to physical, sexual or psychological violence by a current or former intimate partner in the previous 12 months - SDG 5.2.1 (violence sub-domain)',
                        'indicator': 'PT_F_GE15_PS-SX-EM_V_PTNR_12MNTH',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Violence by an intimate partner (SDG 5.2.1)'},
                        {'name': 'Percentage of women (18-29 years) who experienced sexual violence by age 18 years - SDG 16.2.3',
                        'indicator': 'PT_F_18-29_SX-V_AGE-18',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Sexual violence by age 18 (SDG 16.2.3)'},
                        {'name': 'Percentage of students (13-15 years) who reported being bullied on 1 or more days in the past 30 days',
                        'indicator': 'PT_ST_13-15_BUL_30-DYS',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Bullying'},
                        {'name': 'Number of child victims of violence (0-17 years) registered by child/social welfare authorities during the year',
                        'indicator': 'PT_CHLD_VIOLENCE_WELFARE',
                        'suffix': 'child victims of violence',
                        'min_max': False,
                        'button_name': 'Child victims of violence'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['PT_CHLD_1-14_PS-PSY-V_CGVR',
                        'PT_ADLT_PS_NEC',
                        'PT_F_GE15_PS-SX-EM_V_PTNR_12MNTH',
                        'PT_F_18-29_SX-V_AGE-18',
                        'PT_ST_13-15_BUL_30-DYS',
                        'PT_CHLD_VIOLENCE_WELFARE'],
                        'default_graph': 'bar',
                        'default': 'PT_CHLD_1-14_PS-PSY-V_CGVR'}},
                    'CPC': {'NAME': 'Children in alternative care',
                        'CARDS': [{'name': 'Rate of children (0-17 years) in formal alternative care at the end of the year (per 100,000)',
                        'indicator': 'PT_CHLD_INFORMALCARE_RATE',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children in formal alternative care'},
                        {'name': 'Rate of children (0-17 years) in formal residential care at the end of the year (per 100,000)',
                        'indicator': 'PT_CHLD_INRESIDENTIAL_RATE_B',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children in formal residential care'},
                        {'name': 'Rate of children (0-17 years) in formal family-based care at the end of the year (per 100,000)',
                        'indicator': 'PT_CHLD_INCARE_FOSTER_RATE',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children in formal family-based care'},
                        {'name': 'Rate of formal adoption of children (0-17 years) during the year (per 100,000)',
                        'indicator': 'PT_CHLD_ADOPTION_RATE',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Rate of formal adoption of children'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['PT_CHLD_INFORMALCARE_RATE',
                        'PT_CHLD_INRESIDENTIAL_RATE_B',
                        'PT_CHLD_INCARE_FOSTER_RATE',
                        'PT_CHLD_ADOPTION_RATE'],
                        'default_graph': 'bar',
                        'default': 'PT_CHLD_INFORMALCARE_RATE'}},
                    'JUS': {'NAME': 'Justice for children',
                        'CARDS': [{'name': 'Rate of children (0-17 years) in detention at the end of the year (per 100,000)',
                        'indicator': 'JJ_CHLD_DETENTION_RATE',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children in detention'},
                        {'name': 'Rate of children (0-17 years) in pre-sentence detention at the end of the year (per 100,000)',
                        'indicator': 'JJ_CHLD_PRE_SENTENCE_DETENTION_RATE',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children in pre-sentence detention'},
                        {'name': 'Rate of children (0-17 years) in post-sentence detention at the end of the year (per 100,000)',
                        'indicator': 'JJ_CHLD_POST_SENTENCE_DETENTION_RATE',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children in post-sentence detention'},
                        {'name': 'Rate of children (0-17 years) detained in pre-sentence detention during the year (per 100,000)',
                        'indicator': 'JJ_CHLD_ENTER_PRE_SENTENCE_DETENTION_RATE',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children detained in pre-sentence detention during the year'},
                        {'name': 'Percentage of children (0-17 years) sentenced to custodial sentences during the year',
                        'indicator': 'JJ_CHLD_CUSTODIAL_SENTENCE_PROP',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children sentenced to custodial sentences'},
                        {'name': 'Percentage of children (0-17 years) sentenced with alternative measures during the year',
                        'indicator': 'JJ_CHLD_ALTERNATIVE_SENTENCE_PROP',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children sentenced with alternative measures'},
                        {'name': 'Rate of child victims of crime (0-17 years) registered by the police during the year (per 100,000)',
                        'indicator': 'JJ_CHLD_VICTIM_CRIME_RATE',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Child victims of crime'},
                        {'name': 'Rate of child witnesses of crime (0-17 years) registered by the police during the year (per 100,000)',
                        'indicator': 'JJ_CHLD_WITNESS_CRIME_RATE',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Child witnesses of crime '},
                        {'name': 'Unsentenced detainees as a proportion of overall prison population - SDG 16.3.2',
                        'indicator': 'JJ_VC_PRS_UNSNT',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Unsentenced detainees (SDG 16.3.2)'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['JJ_CHLD_DETENTION_RATE',
                        'JJ_CHLD_PRE_SENTENCE_DETENTION_RATE',
                        'JJ_CHLD_POST_SENTENCE_DETENTION_RATE',
                        'JJ_CHLD_ENTER_PRE_SENTENCE_DETENTION_RATE',
                        'JJ_CHLD_CUSTODIAL_SENTENCE_PROP',
                        'JJ_CHLD_ALTERNATIVE_SENTENCE_PROP',
                        'JJ_CHLD_VICTIM_CRIME_RATE',
                        'JJ_CHLD_WITNESS_CRIME_RATE',
                        'JJ_VC_PRS_UNSNT'],
                        'default_graph': 'bar',
                        'default': 'JJ_CHLD_DETENTION_RATE'}},
                    'MAR': {'NAME': 'Child marriage and other harmful practices',
                        'CARDS': [{'name': 'Percentage of women (20-24 years) married or in union before age 18 - SDG 5.3.1 (child marriage sub-domain)',
                        'indicator': 'PT_F_20-24_MRD_U18',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Women aged 20-24 years married or in union before age 18 (SDG 5.3.1)'},
                        {'name': 'Percentage of men (20-24 years) married or in union before age 18',
                        'indicator': 'PT_M_20-24_MRD_U18',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Men aged 20-24 years married or in union before age 18'},
                        {'name': 'Percentage of girls (15-19 years) who are currently married or in union (child marriage sub-domain)',
                        'indicator': 'PT_F_15-19_MRD',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Girls aged 15-19 years who are currently married or in union'},
                        {'name': 'Percentage of boys (15-19 years) who are currently married or in union',
                        'indicator': 'PT_M_15-19_MRD',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Boys aged 15-19 years who are currently married or in union'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['PT_F_20-24_MRD_U18',
                        'PT_M_20-24_MRD_U18',
                        'PT_F_15-19_MRD',
                        'PT_M_15-19_MRD'],
                        'default_graph': 'bar',
                        'default': 'PT_F_20-24_MRD_U18'}},
                    'LAB': {'NAME': 'Child exploitation',
                        'CARDS': [{'name': 'Percentage of children (5-17 years) engaged in child labour (economic activities and household chores) - SDG 8.7.1',
                        'indicator': 'PT_CHLD_5-17_LBR_ECON-HC',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Child labour - economic activities and household chores (SDG 8.7.1)'},
                        {'name': 'Percentage of children (5-17 years) engaged in child labour (economic activities)',
                        'indicator': 'PT_CHLD_5-17_LBR_ECON',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Child labour - economic activities'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['PT_CHLD_5-17_LBR_ECON-HC', 'PT_CHLD_5-17_LBR_ECON'],
                        'default_graph': 'bar',
                        'default': 'PT_CHLD_5-17_LBR_ECON-HC'}}}},
                    'child-participation': {'domain_name': 'Participation and Civil Rights',
                    'page_prefix': 'par',
                    'domain_colour': '#861c3f',
                    'light_domain_colour': '#eca7be',
                    'dark_domain_colour': '#541228',
                    'map_colour': 'Brwnyl',
                    'SUBDOMAINS': {'REG': {'NAME': 'Birth registration and identity',
                        'CARDS': [{'name': 'Percentage of children whose births have been registered with a civil authority - SDG 16.9.1',
                        'indicator': 'PT_CHLD_Y0T4_REG',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Birth registration with a civil authority (SDG 16.9.1)'},
                        {'name': 'Countries with birth registration data that are at least 90 percent complete - SDG 17.19.2',
                        'indicator': 'PP_SG_REG_BRTH90N',
                        'suffix': 'countries',
                        'min_max': False,
                        'button_name': 'Birth registration data (SDG 17.19.2)'},
                        {'name': 'Countries with death registration data that are at least 75 percent complete - SDG 17.19.2',
                        'indicator': 'PP_SG_REG_DETH75N',
                        'suffix': 'countries',
                        'min_max': False,
                        'button_name': 'Death registration data (SDG 17.19.2)'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['PT_CHLD_Y0T4_REG',
                        'PP_SG_REG_BRTH90N',
                        'PP_SG_REG_DETH75N'],
                        'default_graph': 'bar',
                        'default': 'PT_CHLD_Y0T4_REG'}},
                    'PAR': {'NAME': 'Child participation',
                        'CARDS': [{'name': 'No indicators available yet for this sub-domain',
                        'indicator': 'PART-INDICATOR',
                        'suffix': 'No indicator chosen.',
                        'min_max': True,
                        'button_name': 'No indicators available yet for this sub-domain.'},],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': [],
                        'default_graph': 'bar',
                        'default': 'PART-INDICATOR'}},   
                    'CIV': {'NAME': 'Civil and political freedoms',
                        'CARDS': [{'name': 'No indicators available yet for this sub-domain',
                        'indicator': 'CIVIL-INDICATOR',
                        'suffix': 'No indicator chosen.',
                        'min_max': True,
                        'button_name': 'No indicators available yet for this sub-domain.'},],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': [],
                        'default_graph': 'bar',
                        'default': 'CIVIL-INDICATOR'}},                                                
                    'ICT': {'NAME': 'Information, internet and protection of privacy',
                        'CARDS': [{'name': 'Internet users per 100 inhabitants - SDG 17.8.1',
                        'indicator': 'PP_IT_USE_ii99',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Internet use (SDG 17.8.1)'},
                        {'name': 'Percentage of youth and adults with ICT skill: writing a computer program using a specialized programming language - SDG 4.4.1',
                        'indicator': 'PP_SE_ADT_ACTS_PRGM',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'ICT skills: writing a computer program using a specialized programming language (SDG 4.4.1)'},
                        {'name': 'Percentage of youth and adults with ICT skill: sending e-mails with attached files - SDG 4.4.1',
                        'indicator': 'PP_SE_ADT_ACTS_ATCH',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'ICT skills: sending e-mails with attached files (SDG 4.4.1)'},
                        {'name': 'Percentage of youth and adults with ICT skill: finding, downloading, installing and configuring software - SDG 4.4.1',
                        'indicator': 'PP_SE_ADT_ACTS_SFWR',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'ICT skills: finding, downloading, installing and configuring software (SDG 4.4.1)'},
                        {'name': 'Percentage of population who used the internet in the last 3 months and managed access to their personal data (information sub-domain)',
                        'indicator': 'ICT_PERSONAL_DATA',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Privacy and protection of personal data'},
                        {'name': 'Percentage of population who limited their personal internet activities in the last 12 months due to security concerns',
                        'indicator': 'ICT_SECURITY_CONCERN',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Internet security concerns'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['PP_IT_USE_ii99',
                        'PP_SE_ADT_ACTS_PRGM',
                        'PP_SE_ADT_ACTS_ATCH',
                        'PP_SE_ADT_ACTS_SFWR',
                        'ICT_PERSONAL_DATA',
                        'ICT_SECURITY_CONCERN'],
                        'default_graph': 'bar',
                        'default': 'PP_IT_USE_ii99'}}}},
                    'child-poverty': {'domain_name': 'Poverty and Social Protection',
                    'page_prefix': 'pov',
                    'domain_colour': '#4c8cbb',
                    'light_domain_colour': '#c0d7e7',
                    'dark_domain_colour': '#1c374a',
                    'map_colour': 'GnBu',
                    'SUBDOMAINS': {'SPS': {'NAME': 'Social protection system',
                        'CARDS': [{'name': 'Percentage of population covered by at least one social protection benefit - SDG 1.3.1',
                        'indicator': 'PV_SI_COV_BENFTS',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Population covered by at least one social protection benefit (SDG 1.3.1)'},
                        {'name': 'Percentage of children/households receiving child/family cash benefit - SDG 1.3.1',
                        'indicator': 'PV_SI_COV_CHLD',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children/households receiving child/family cash benefit (SDG 1.3.1)'},
                        {'name': 'Percentage of mothers with newborns receiving maternity cash benefit - SDG 1.3.1',
                        'indicator': 'PV_SI_COV_MATNL',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Mothers with newborns receiving maternity cash benefit (SDG 1.3.1)'},
                        {'name': 'Percentage of population with severe disabilities receiving disability cash benefit - SDG 1.3.1 (social protection sub-domain)',
                        'indicator': 'PV_SI_COV_DISAB',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Population with severe disabilities receiving disability cash benefit (SDG 1.3.1)'},
                        {'name': 'Percentage of unemployed persons receiving unemployment cash benefit - SDG 1.3.1',
                        'indicator': 'PV_SI_COV_UEMP',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Unemployed persons receiving unemployment cash benefit (SDG 1.3.1)'},
                        {'name': 'Percentage of vulnerable population receiving social assistance cash benefit - SDG 1.3.1',
                        'indicator': 'PV_SI_COV_VULN',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Vulnerable population receiving social assistance cash benefit  (SDG 1.3.1)'},
                        {'name': 'Percentage of poor population receiving social assistance cash benefit - SDG 1.3.1',
                        'indicator': 'PV_SI_COV_POOR',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Poor population receiving social assistance cash benefit (SDG 1.3.1)'},
                        {'name': 'Expenditure on family-children benefits (% of expenditure on social benefits) (social protection sub-domain)',
                        'indicator': 'EC_EXP_FAM_CHLD_EXP',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Expenditure on family-children benefits'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['PV_SI_COV_BENFTS',
                        'PV_SI_COV_CHLD',
                        'PV_SI_COV_MATNL',
                        'PV_SI_COV_DISAB',
                        'PV_SI_COV_UEMP',
                        'PV_SI_COV_VULN',
                        'PV_SI_COV_POOR',
                        'EC_EXP_FAM_CHLD_EXP'],
                        'default_graph': 'bar',
                        'default': 'PV_SI_COV_BENFTS'}},
                    'MAT': {'NAME': 'Child poverty and material deprivation',
                        'CARDS': [{'name': 'Poverty headcount ratio at $6.85 a day (2017 PPP)',
                        'indicator': 'SI_POV_UMIC',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Poverty headcount ratio at $6.85 a day'},
                        {'name': 'Percentage of population living below the national poverty line - SDG 1.2.1',
                        'indicator': 'PV_SDG_SI_POV_NAHC',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Population living below the national poverty line (SDG 1.2.1)'},
                        {'name': 'People at risk of poverty or social exclusion',
                        'indicator': 'PV_AROPE',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'People at risk of poverty or social exclusion'},
                        {'name': 'Severe material and social deprivation rate',
                        'indicator': 'PV_SEV_MAT_SOC_DPRT',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Severe material and social deprivation rate'},
                        {'name': 'At-risk-of-poverty rate by threshold: 60% of national median equivalized disposable income after social transfers',
                        'indicator': 'PV_AROPRT',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'At-risk-of-poverty rate'},
                        {'name': 'People living in households with very low work intensity',
                        'indicator': 'PV_LOW_WORK',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Low work intensity'},
                        {'name': 'Share of households with dependent children with inability to afford a meal with protein every second day',
                        'indicator': 'PV_INABLE_PROTEIN',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Inability to afford a meal with protein'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['SI_POV_UMIC',
                        'PV_SDG_SI_POV_NAHC',
                        'PV_AROPE',
                        'PV_SEV_MAT_SOC_DPRT',
                        'PV_AROPRT',
                        'PV_LOW_WORK',
                        'PV_INABLE_PROTEIN'],
                        'default_graph': 'bar',
                        'default': 'SI_POV_UMIC'}},
                    'WSH': {'NAME': 'Water and sanitation',
                        'CARDS': [{'name': 'Percentage of population using safely managed drinking water services - SDG 6.1.1',
                        'indicator': 'WS_PPL_W-SM',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Safely managed drinking water services (SDG 6.1.1)'},
                        {'name': 'Percentage of population using safely managed sanitation services - SDG 6.2.1',
                        'indicator': 'WS_PPL_S-SM',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Safely managed sanitation services (SDG 6.1.2)'},
                        {'name': 'Percentage of population having neither a bath, nor a shower, nor indoor flushing toilet in their household',
                        'indicator': 'HT_NO_BTH_SHW_FLSH',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'No bath, shower, or indoor flushing toilet in household'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['WS_PPL_W-SM', 'WS_PPL_S-SM', 'HT_NO_BTH_SHW_FLSH'],
                        'default_graph': 'bar',
                        'default': 'WS_PPL_W-SM'}}}},
                    'child-cross-cutting': {'domain_name': 'Cross-Cutting',
                    'page_prefix': 'cci',
                    'domain_colour': '#ec5e24',
                    'light_domain_colour': '#f4d5c0',
                    'dark_domain_colour': '#903717',
                    'map_colour': 'Oranges',
                    'SUBDOMAINS': {'GND': {'NAME': 'Gender',
                        'CARDS': [{'name': 'Gender Development Index',
                        'indicator': 'EC_GDI',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Gender Development Index '},
                        {'name': 'Gender Inequality Index',
                        'indicator': 'EC_GII',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Gender Inequality Index'},
                        {'name': 'Adolescent birth rate - SDG 3.7.2 (gender sub-domain)',
                        'indicator': 'FT_SP_DYN_ADKL-GND',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Adolescent birth rate (SDG 3.7.2)'},
                        {'name': 'Adjusted gender parity index for upper secondary education completion rate - SDG 4.5.1',
                        'indicator': 'EDU_SE_AGP_CPRA_L3',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Gender parity index for completion rate (SDG 4.5.1)'},
                        {'name': 'Adjusted gender parity index for students at the end of lower secondary education achieving a minimum proficiency level in mathematics - SDG 4.5.1',
                        'indicator': 'EDU_SE_TOT_GPI_L2_MAT',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Gender parity index for achieving proficiency in math (SDG 4.5.1)'},
                        {'name': 'Adjusted gender parity index for students at the end of lower secondary education achieving a minimum proficiency level in reading - SDG 4.5.1',
                        'indicator': 'EDU_SE_TOT_GPI_L2_REA',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Gender parity index for achieving proficiency in reading (SDG 4.5.1)'},
                        {'name': 'Percentage of children (1-14 years) who experienced any physical punishment and/or psychological aggression by caregivers - SDG 16.2.1 (gender sub-domain)',
                        'indicator': 'PT_CHLD_1-14_PS-PSY-V_CGVR-GND',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Physical punishment and/or psychological aggression by caregivers (SDG 16.2.1)'},
                        {'name': 'Percentage of ever-partnered women and girls (15 years and older) subjected to physical, sexual or psychological violence by a current or former intimate partner in the previous 12 months - SDG 5.2.1 (gender sub-domain)',
                        'indicator': 'PT_F_GE15_PS-SX-EM_V_PTNR_12MNTH-GND',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Violence by an intimate partner (SDG 5.2.1)'},
                        {'name': 'Percentage of girls (15-19 years) who are currently married or in union (gender sub-domain)',
                        'indicator': 'PT_F_15-19_MRD-GND',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Girls aged 15-19 years who are currently married or in union'},
                        {'name': 'Percentage of women (20-24 years) married or in union before age 18 - SDG 5.3.1. (gender sub-domain)',
                        'indicator': 'PT_F_20-24_MRD_U18-GND',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Women aged 20-24 years married or in union before age 18 (SDG 5.3.1)'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['EC_GDI',
                        'EC_GII',
                        'FT_SP_DYN_ADKL-GND',
                        'EDU_SE_AGP_CPRA_L3',
                        'EDU_SE_TOT_GPI_L2_MAT',
                        'EDU_SE_TOT_GPI_L2_REA-GND',
                        'PT_CHLD_1-14_PS-PSY-V_CGVR-GND',
                        'PT_F_GE15_PS-SX-EM_V_PTNR_12MNTH-GND',
                        'PT_F_15-19_MRD-GND',
                        'PT_F_20-24_MRD_U18-GND'],
                        'default_graph': 'bar',
                        'default': 'EC_GDI-GND'}},
                    'DIS': {'NAME': 'Disability',
                        'CARDS': [{'name': 'Percentage of children (0-17 years) registered as having disabilities at the end of the year',
                        'indicator': 'HT_REG_CHLD_DISAB_PROP',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children registered as having disabilities'},
                        {'name': 'Percentage of children (0-17 years) newly registered as having disabilities during the year',
                        'indicator': 'HT_NEW_REG_CHLD_DISAB_PROP',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children newly registered as having disabilities'},
                        {'name': 'Percentage of primary schools with access to adapted infrastructure and materials for students with disabilities - SDG 4.a.1 (disability sub-domain)',
                        'indicator': 'EDU_SDG_SCH_L1-DIS',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Primary schools adapted infrastructure and materials (SDG 4.a.1)'},
                        {'name': 'Percentage of lower secondary schools with access to adapted infrastructure and materials for students with disabilities - SDG 4.a.1 (disability sub-domain)',
                        'indicator': 'EDU_SDG_SCH_L2-DIS',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Lower secondary schools with adapted infrastructure and materials (SDG 4.a.1)'},
                        {'name': 'Percentage of upper secondary schools with access to adapted infrastructure and materials for students with disabilities - SDG 4.a.1 (disability sub-domain)',
                        'indicator': 'EDU_SDG_SCH_L3-DIS',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Upper secondary schools with adapted infrastructure and materials (SDG 4.a.1)'},
                        {'name': 'Percentage of children with disabilities (0-17 years) in formal residential care at the end of the year',
                        'indicator': 'PT_CHLD_DISAB_INRESIDENTIAL_PROP',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children with disabilities in formal residential care'},
                        {'name': 'Percentage of children with disabilities (0-17 years) in formal family-based care at the end of the year',
                        'indicator': 'PT_CHLD_DISAB_INFAMILY_PROP',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children with disabilities in formal family-based care'},
                        {'name': 'Percentage of children with disabilities (0-17 years) in formal foster care of the total number of children in formal family-based care at the end of the year',
                        'indicator': 'PT_CHLD_DISAB_INFOSTER_PROP',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children with disabilities in formal foster care of the total number of children in formal family-based care'},
                        {'name': 'Percentage of population with severe disabilities receiving disability cash benefit - SDG 1.3.1 (disability sub-domain)',
                        'indicator': 'PV_SI_COV_DISAB-DIS',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Population with severe disabilities receiving disability cash benefit (SDG 1.3.1)'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['HT_REG_CHLD_DISAB_PROP',
                        'HT_NEW_REG_CHLD_DISAB_PROP',
                        'EDU_SDG_SCH_L1-DIS',
                        'EDU_SDG_SCH_L2-DIS',
                        'EDU_SDG_SCH_L3-DIS',
                        'PT_CHLD_DISAB_INRESIDENTIAL_PROP',
                        'PT_CHLD_DISAB_INFAMILY_PROP',
                        'PT_CHLD_DISAB_INFOSTER_PROP',
                        'PV_SI_COV_DISAB-DIS'],
                        'default_graph': 'bar',
                        'default': 'HT_REG_CHLD_DISAB_PROP'}},
                    'ECD': {'NAME': 'Early childhood development',
                        'CARDS': [{'name': '4.2.1. Percentage of children (36-59 months) developmentally on track in at least 3 of the 4 following domains: literacy-numeracy, physical, social-emotional and learning',
                        'indicator': 'ECD_CHLD_36-59M_LMPSL',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Early Childhood Development Index (SDG 4.2.1)'},
                        {'name': 'Neonatal mortality rate - SDG 3.2.2 (ECD sub-domain)',
                        'indicator': 'CME_MRM0-ECD',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Neonatal mortality rate (SDG 3.2.2)'},
                        {'name': 'Percentage of infants (under 6 months) who are exclusively breastfed (ECD sub-domain)',
                        'indicator': 'NT_BF_EXBF-ECD',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Exclusive breastfeeding'},
                        {'name': 'Percentage of children (36-59 months) with whom any adult household member has engaged in 4 or more activities to provide early stimulation and responsive care in the last 3 days',
                        'indicator': 'ECD_CHLD_24-59M_ADLT_SRC',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Engagement in early stimulation activities with adult'},
                        {'name': 'Participation in organized learning (adjusted net enrolment rate, one year before official primary entry age - administrative data) - SDG 4.2.2 (ECD sub-domain)',
                        'indicator': 'EDUNF_NERA_L1_UNDER1-ECD',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Participation in organized learning - administrative data (SDG 4.2.2)'},
                        {'name': 'Children aged less than 3 years in formal childcare',
                        'indicator': 'ECD_IN_CHILDCARE',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children in formal childcare'},
                        {'name': 'Pupils from age 3 to the starting age of compulsory education at primary level (ECD sub-domain)',
                        'indicator': 'ECD_EARLY_EDU',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Pupils from age 3 to the starting age of compulsory education at primary level'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['ECD_CHLD_36-59M_LMPSL',
                        'CME_MRM0-ECD',
                        'NT_BF_EXBF-ECD',
                        'ECD_CHLD_24-59M_ADLT_SRC',
                        'EDUNF_NERA_L1_UNDER1-ECD',
                        'ECD_IN_CHILDCARE',
                        'ECD_EARLY_EDU-ECD'],
                        'default_graph': 'bar',
                        'default': 'ECD_CHLD_36-59M_LMPSL'}},
                    'ODA': {'NAME': 'Adolescents',
                        'CARDS': [{'name': 'Adolescent birth rate - SDG 3.7.2 (adolescents sub-domain)',
                        'indicator': 'FT_SP_DYN_ADKL-ADO',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Adolescent birth rate (SDG 3.7.2)'},
                        {'name': 'Suicide mortality rate - SDG 3.4.2 (adolescents sub-domain)',
                        'indicator': 'MT_SDG_SUICIDE-ADO',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Suicide rate (SDG 3.4.2)'},
                        {'name': 'Percentage of youth (15-24 years) not in education, employment or training - SDG 8.6.1 (adolescents sub-domain)',
                        'indicator': 'EDU_SDG_YOUTH_NEET-ADO',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': ' Percentage of youth not in education, employment or training (SDG 8.6.1)'},
                        {'name': 'Percentage of children at the end of lower secondary education reaching minimum proficiency in math - SDG 4.1.1 (adolescents sub-domain)',
                        'indicator': 'EDU_SDG_STU_L2_GLAST_MAT-ADO',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children at the end of lower secondary education reaching minimum proficiency in math (SDG 4.1.1)'},
                        {'name': 'Percentage of children at the end of lower secondary education reaching minimum proficiency in reading - SDG 4.1.1 (adolescents sub-domain)',
                        'indicator': 'EDU_SDG_STU_L2_GLAST_REA-ADO',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Children at the end of lower secondary education reaching minimum proficiency in reading (SDG 4.1.1)'},
                        {'name': 'Upper secondary education completion rate - SDG 4.1.2 (adolescents sub-domain)',
                        'indicator': 'EDUNF_CR_L3-ADO',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Completion rate - upper secondary education (SDG 4.1.2)'},
                        {'name': 'Percentage of children (1-14 years) who experienced any physical punishment and/or psychological aggression by caregivers - SDG 16.2.1 (adolescents sub-domain)',
                        'indicator': 'PT_CHLD_1-14_PS-PSY-V_CGVR-ADO',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Physical punishment and/or psychological aggression by caregivers (SDG 16.2.1)'},
                        {'name': 'Percentage of population who used the internet in the last 3 months and managed access to their personal data (adolescents sub-domain)',
                        'indicator': 'ICT_PERSONAL_DATA-ADO',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Privacy and protection of personal data'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['FT_SP_DYN_ADKL-ADO',
                        'MT_SDG_SUICIDE-ADO',
                        'EDU_SDG_YOUTH_NEET-ADO',
                        'EDU_SDG_STU_L2_GLAST_MAT-ADO',
                        'EDU_SDG_STU_L2_GLAST_REA-ADO',
                        'EDUNF_CR_L3-ADO',
                        'PT_CHLD_1-14_PS-PSY-V_CGVR-ADO',
                        'ICT_PERSONAL_DATA-ADO'],
                        'default_graph': 'bar',
                        'default': 'FT_SP_DYN_ADKL-ADO'}},
                    'ENV': {'NAME': 'Environment and climate change',
                        'CARDS': [{'name': "Children's Climate Risk Index (CCRI)",
                        'indicator': 'CR_CCRI',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': "Children's Climate Risk Index"},
                        {'name': "CCRI Pillar 1: Children's exposure to climate and environmental hazards, shocks and stresses",
                        'indicator': 'CR_CCRI_EXP_CESS',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'CCRI Pillar 1'},
                        {'name': "CCRI Pillar 2: Children's vulnerability to climate and environmental hazards, shocks and stresses",
                        'indicator': 'CR_CCRI_VUL_ES',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'CCRI Pillar 2'},
                        {'name': 'Percentage of population with primary reliance on clean fuels and technology - SDG 7.1.2',
                        'indicator': 'CR_EG_EGY_CLEAN',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Reliance on clean fuels and technology (SDG 7.1.2)'},
                        {'name': 'Age-standardized mortality rate attributed to household and ambient air pollution - SDG 3.9.1',
                        'indicator': 'CR_SH_STA_ASAIRP',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Mortailty rate - household and ambient air pollution  (SDG 3.9.1)'},
                        {'name': 'Age-standardized mortality rate attributed to household air pollution - SDG 3.9.1',
                        'indicator': 'CR_SH_HAP_ASMORT',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Mortailty rate - household air pollution (SDG 3.9.1)'},
                        {'name': 'Age-standardized mortality rate attributed to ambient air pollution - SDG 3.9.1',
                        'indicator': 'CR_SH_AAP_ASMORT',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Mortailty rate - ambient air pollution (SDG 3.9.1)'},
                        {'name': 'Annual mean concentration of particles PM2.5 (ug/m3) - SDG 11.6.2',
                        'indicator': 'HT_SDG_PM25',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Air quality (SDG 11.6.2)'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['CR_CCRI',
                        'CR_CCRI_EXP_CESS',
                        'CR_CCRI_VUL_ES',
                        'CR_EG_EGY_CLEAN',
                        'CR_SH_STA_ASAIRP',
                        'CR_SH_HAP_ASMORT',
                        'CR_SH_AAP_ASMORT',
                        'HT_SDG_PM25'],
                        'default_graph': 'bar',
                        'default': 'CR_CCRI'}},
                    'DCD': {'NAME': 'Disaster, conflict and displacement',
                        'CARDS': [{'name': 'INFORM Risk Index',
                        'indicator': 'CR_INFORM',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'INFORM Risk Index'},
                        {'name': 'Number of deaths and missing persons attributed to disasters (per 100,000 population) - SDG 11.5.1',
                        'indicator': 'CR_VC_DSR_MTMP',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Deaths and missing persons attributed to disasters (SDG 11.5.1)'},
                        {'name': 'Number of directly affected persons attributed to disasters (per 100,000 population) - SDG 11.5.1',
                        'indicator': 'CR_VC_DSR_DAFF',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'Persons directly affected by disasters (SDG 11.5.1)'},
                        {'name': 'Score of adoption and implementation of national DRR strategies in line with the Sendai Framework - SDG 1.5.3',
                        'indicator': 'CR_SG_DSR_LGRGSR',
                        'suffix': min_max_card_suffix,
                        'min_max': True,
                        'button_name': 'National DRR strategies (SDG 11.5.3)'},
                        {'name': 'Number of first time asylum applicants',
                        'indicator': 'DM_ASYL_FRST',
                        'suffix': 'persons',
                        'min_max': False,
                        'button_name': 'First time asylum applicants'},
                        {'name': 'Number of asylum applicants considered to be unaccompanied minors',
                        'indicator': 'DM_ASYL_UASC',
                        'suffix': 'persons',
                        'min_max': False,
                        'button_name': 'Unaccompanied minors'}],
                        'AIO_AREA': {'graphs': graphs_dict,
                        'indicators': ['CR_INFORM',
                        'CR_VC_DSR_MTMP',
                        'CR_VC_DSR_DAFF',
                        'CR_SG_DSR_LGRGSR',
                        'DM_ASYL_FRST',
                        'DM_ASYL_UASC'],
                        'default_graph': 'bar',
                        'default': 'CR_INFORM'}}}}}

